name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Change directory to student_hub
        run: cd student_hub

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0

      - name: Disable Flutter CLI animations
        run: flutter config --no-cli-animations

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter test
        run: flutter test

      - name: Flutter build APK
        run: flutter build apk

      - name: Flutter build appbundle
        run: flutter build appbundle
